// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgovpoYq8-WIuviYF0-_VL06SuhncQBjA',
    appId: '1:1000891632492:web:6634f0f968fa21397cc149',
    messagingSenderId: '1000891632492',
    projectId: 'my-case-project',
    authDomain: 'my-case-project.firebaseapp.com',
    storageBucket: 'my-case-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCDsOmWjBTTU7fnzp0b9fgetSlJOyiwag',
    appId: '1:1000891632492:android:eb016737773489597cc149',
    messagingSenderId: '1000891632492',
    projectId: 'my-case-project',
    storageBucket: 'my-case-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5jpjP79XiCNSkTZHJItnoXhEOzf0OVHY',
    appId: '1:1000891632492:ios:52693a04e89159207cc149',
    messagingSenderId: '1000891632492',
    projectId: 'my-case-project',
    storageBucket: 'my-case-project.appspot.com',
    iosClientId: '1000891632492-grdvkeb5fgbfs9vq7urtb6dba43efn23.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCaseDeneme2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5jpjP79XiCNSkTZHJItnoXhEOzf0OVHY',
    appId: '1:1000891632492:ios:52693a04e89159207cc149',
    messagingSenderId: '1000891632492',
    projectId: 'my-case-project',
    storageBucket: 'my-case-project.appspot.com',
    iosClientId: '1000891632492-grdvkeb5fgbfs9vq7urtb6dba43efn23.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCaseDeneme2',
  );
}
